### ISSUE TITLE
Does this plugin conflict with TamperMonkey userscript installing?

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#10]
I can't install userscripts now on https://greasyfork.org

When I try to install some userscript .js

It leads to chrome-extension://onnbmgmepodkilcbdodhfepllfmafmlj/html/install.html#https://greasyfork.org/scripts/5367-youtube-auto-subtitle-downloader-v11/code/Youtube%20Auto%20Subtitle%20Downloader%20v11.user.js

**Comment by SanderRonde** [comment]
Hey, sorry for the inconvenience. At the moment there's a bug with the installation page for userscripts for this extension, that should be fixed in a while, in the meantime you can just disable the extension in chrome://extensions.

About the conflict with TamperMonkey. Yes it does probably conflict with TamperMonkey. This is because both extensions do the same thing (of course I feel like this one has more features). This means that they both need to install userscripts when the "install" button is clicked. Unfortunately there is no way to know whether TamperMonkey is also running and since GreasyFork hasn't been made to be compatible with multiple userscript handlers, this extension uses the same method as TamperMonkey does, which probably causes it to happen.

If you want to just use GreaseMonkey instead simply turn off the extension before installing any scripts. In the future I might add an option for that but right now I'm a bit busy so it might take a while.
