### ISSUE TITLE
Unclear how to share code in scripts 

### ISSUE THREAD

**Issue by robinchew** [SanderRonde/CustomRightClickMenu#13]
Hi Sander,

I want to share a function between scripts. For example in the image below, I want all context menu options to share and run the `addLink` function. Currently I'm resorting to `localStorage` to keep the `addLink` function as string, and `eval` it to declare.

![custom-context](https://user-images.githubusercontent.com/7122710/29209436-0dd90c52-7ec1-11e7-901e-3ac14027d940.png)

Thanks for the extension!
Robin

**Comment by SanderRonde** [comment]
Hey,

The best way to share code is to use a library. This can be done by hitting the fullscreen button, going to libraries, clicking "add your own", selecting code and inputting the code you want like in the image below.

![image](https://user-images.githubusercontent.com/5385012/29217877-4e202f56-7eb3-11e7-9365-4d7484cc2795.png)

Then make sure the library with the name you just gave it (myLibrary in this case), is checked on any other scripts you want to have it active. Just go to the libraries section again and click the name (myLibrary) until it has a checkbox (or click it again to disable it on this script), like in the image below.

![image](https://user-images.githubusercontent.com/5385012/29217939-7e0c4f7e-7eb3-11e7-961d-b71dd6a64003.png)

The only negative thing is that whenever you want to update your "library", you'll have to give it a new name and you'll have to re-check the new name. This is done because normally libraries (like jquery, react etc), use versioning, and using titles like "jquery v1.0", "jquery v1.5" ensures you can use any version you want as using the latest one is not always your goal.

I hope this can help you.

**Comment by robinchew** [comment]
Thank you very much, I am completely unaware of this feature! I didn't notice that tiny arrow that exposes that left side bar. This should probably be documented under 'Developing Scripts' in README.md. I say just the screenshot itself with no explanation will be worth a thousand words.

Regarding the negative bit about updating the library, isn't the real issue the inability to delete a library?

**Comment by SanderRonde** [comment]
The sidebar should have been expanded the first time, which in theory should have made people aware of its existence, but you're right that I should probably document it as it contains some pretty essential features. 

Regarding the it not being removable bit, it's supposed to delete itself when no script is using a library, however that seems to not work and your idea is a lot clearer and easier to use so I'll implement that instead when I get the chance.
