### ISSUE TITLE
Dissallow Duplicate node names per menu

### ISSUE THREAD

**Issue by ToastyStoemp** [SanderRonde/CustomRightClickMenu#18]

**Comment by SanderRonde** [comment]
There's not really many reasons to disallow this (at least that I can think of), the only one being that searching for a node by name through the CRM API would only return the first match instead of all, but that shouldn't be a big problem at all as there's multiple ways to search for nodes. There are also bound to be some people that have some use for this (for example a script that auto-generates child nodes in a menu with the same name), and I don't really see a reason to disallow this (unless you have some more reasons).
