### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [SanderRonde/CustomRightClickMenu#22]
Hi @SanderRonde 

My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by SanderRonde** [comment]
Hi,

I'd love that actually. As you might have seen I'm terrible at creating logos so I can definitely use the help.

**Comment by tjulises** [comment]
I'd also like to ask some questions (towards the logo-making)

@SanderRonde 
What's the name that should be displayed on the logo, If there should be any.

How would you describe this project,
what is it intended to do?

What would you like this logo to transmit?

this little details are going to help me transmit what it's supposed to.

I'll look forward for your reply, cheers!

**Comment by SanderRonde** [comment]
Seeing as people are mainly going to be seeing it at the size of a chrome icon (so 16x16) I don't think having more than 1 (if any) letter on the logo would be useful since it would be hard to read.

I'd describe this project as a way to customize your browser's contextmenu. A way to basically be able to do anything at the (right) click of a button. 

I think I'd like to logo to transmit customizability and personalization with some programming elements in it to emphasize that part of the project.

Also don't feel limited by the name of the project. If you feel like there's a better name for this project that's not as descriptive but also not completely arbitrary (think uBlock and stylish) feel free to suggest it since the current name is obviously a bit too literal.

Thank you very much for doing this, I look forward to what you come up with!

**Comment by tjulises** [comment]
Hello @SanderRonde  ,
This is what I came up with,
If you have any suggestions I'd like to know!
I hope you like it.

![custom](https://user-images.githubusercontent.com/39039587/40893842-04aa3ba6-6773-11e8-9c9e-f77480b59dac.jpg)

**Comment by SanderRonde** [comment]
I think they're absolutely amazing! I think I like the third one most and I'd love to make it the icon for this project. Can you send me the original image file so I can implement it. When I credit you is there any website or something I can link?

**Comment by tjulises** [comment]
Ok no problem, which one should I upload # 3 or 3 a, b or c? 
@SanderRonde 
I'll give you all the necessary and ready to use files in a google drive link. Looking forward for your feedback

**Comment by SanderRonde** [comment]
It would be best if you could upload all of them (so # 3 the main image and 3 a, b and c) so I can use all of them if I need to.

**Comment by karinakozarova** [comment]
Hey @tjulises, I am the developer of [Arduino Dancer]( https://github.com/karinakozarova/Arduino-Dancer) and I really like your work. :heart_eyes:  We will be very happy if you decide that our project is worth a time. For more info feel free to open an issue at the Arduino Dancer repo or contact me directly.

**Comment by tjulises** [comment]
Hi @karinakozarova   Glad you liked my work, will be a pleasure to work with you :+1:

**Comment by tjulises** [comment]
@SanderRonde   When I make the pr I'll upload all the he variations, but you must tell me which one to upload to the readme.

**Comment by SanderRonde** [comment]
For the readme I think the leftmost # 3 looks the best (the one without a background). However, could you maybe rotate it the same way it's rotated in 3a, 3b and 3c (so just a 45 degree rotate)? Thanks!

**Comment by SanderRonde** [comment]
Using them off of Google drive would be easiest. I'll add them to the repo later on after I've created a folder to hold all of them.

**Comment by tjulises** [comment]
Here's the [google drive](https://drive.google.com/open?id=1hvRMGnjSv4puED8WplyAYAJgkJBp8PhZ) link with its monochromatic versions and all its ready to use files for any future updates! @SanderRonde 

I've sended also a pull request with the choosen png with its 45° rotation as wanted!

**Comment by tjulises** [comment]
Ill close this issue now, everything is already merged #23
