### ISSUE TITLE
Question: how to add script to menu item name

### ISSUE THREAD

**Issue by undrline** [SanderRonde/CustomRightClickMenu#25]
Brand new to the extension.  It appears to work with the [Install Chrome Extensions Addon](https://addons.opera.com/en/extensions/details/install-chrome-extensions/) for Opera.  But, don't get hung up on that.    Don't worry about the fact that I'm doing this in Opera.

What I'm trying to do is duplicate Chrome's native "Go to %s" where `%s` is selected text that's not hyperlinked.  

EDIT:
Nevermind  `Go to %s` worked.  I need to learn more about the code.

Here's my duplicate of the Chrome function
```
var query;
var url = "%s";
if (crmAPI.getSelection()) {
	query = crmAPI.getSelection();
} else {
	query = window.prompt('Please enter a search query');
}
if (query) {
	window.open(url.replace(/%s/g,query), '_blank');
}
```

**Comment by SanderRonde** [comment]
Yeah I don't think I've explained it anywhere so I don't fault you for not knowing it. I'll try and show it more clearly somewhere. 
Regarding using the Opera browser, the extension is actually undergoing review for initial publication on the opera addon store so in theory you can download it for Opera in a while. In practice however it's been around a month since certification began so I have no clue how long it's going to take still.

I'll close this issue for now as you've fixed it yourself.
