### ISSUE TITLE
Cannot click hold to move items

### ISSUE THREAD

**Issue by tedzhu** [SanderRonde/CustomRightClickMenu#30]
New user here, thanks for working on this

When I followed the instruction "Click and hold the three stripes () to drag the nodes", it highlighted the current node, but it won't move.

"Also somehow related, is it possible to create / move a node to root? Same level as "Custom Menu"

**Comment by SanderRonde** [comment]
Hey, regarding the issue, this is a known bug which should be fixed in the next release, thank you for reporting it though. I'll keep this issue open until the next release has been pushed as a message for anyone else running into it. Regarding your question, no this is unfortunately not possible. Chrome (and other browsers) only allow a single root node per extension. The only thing you can do is rename it.

**Comment by tedzhu** [comment]
Got it, thanks!

**Comment by SanderRonde** [comment]
The bug should be fixed with the latest release (1862783913dc31a6b8c8169b8915d80250623995)
