### ISSUE TITLE
How can I open a link in chrome incognito tab

### ISSUE THREAD

**Issue by duongtuannhat** [SanderRonde/CustomRightClickMenu#31]

**Comment by SanderRonde** [comment]
Unfortunately there's no easy way to do this. Chrome (and other browsers) are pretty strict with shielding off incognito. However, you can launch the chrome program in incognito mode and pass the URL you want as an argument. This might be a bit tough to do if you're not that experienced with the commandline and how windows works (I'll assume you're on windows).

The goal is to launch the chrome process with the --incognito flag and the new URL as the argument. This will open that tab in incognito mode. Here's a link to the syntax for the flag: https://stackoverflow.com/questions/11857123/how-to-open-a-url-in-chrome-incognito-mode. In order to do that you need to register a new URL scheme that opens given parameter in incognito mode. You can use the "opening a desktop program" wiki page for setting up a custom scheme, which can be found here: https://github.com/SanderRonde/CustomRightClickMenu/wiki/Opening-a-desktop-program. The only tricky part is getting the syntax of the custom URI scheme correct (i.e. the order of the arguments should be correct). For some help on that check out this page: https://msdn.microsoft.com/en-us/windows/desktop/aa767914. Unfortunately I'm not an expert on the area of custom URI schemes so I can't help you a lot in that regard. It's also for a big part a matter of trying until you get it right.

I hope this can help you somehow and if there's anything else I can help you with please let me know.

**Comment by tbmuc** [comment]
Hello, may I ask you a followup question.

I created a registry entry for "mychrome" whith the value ""C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "%1" "--incognito""

When I call mychrome:// from the browser, a incognito window is opened but I have no clue, how to pass the value (eg). mychrome://http://www.google.de does not work, neither    mychrome://abc .

**Comment by SanderRonde** [comment]
I tried to do this myself as well and found that the reason it doesn't work is the following. %1 passes the full matched scheme to the target application. This means that if you run mychrome://abc chrome gets run with "mychrome://abc". Since this is, again, a URI scheme (it's the very same one you passed in the first place), it will basically keep infinitely opening new chrome windows. I assume someone has added a check for that in the chrome code because that's not what happens.

What you can see though, is that if you invalidate the scheme (for example you don't use "%1" but "'%1'" with added quotes inside), it will open the passed URL but it's invalid. Because of this there's no infinite loop and it opens it. 

The result here is that it's not directly possible to open a URL in chrome, as chrome gets the whole scheme as a parameter and doesn't know what to do with it. Something you can do though, is to create/use a different program that slices out the custom scheme and then finally calls chrome with the sliced version. Fortunately, I've gone ahead and created a program that does that [over here](https://gist.github.com/SanderRonde/4c0ef890bcf3df89864678dfa7204f08). All you need for the program is python. Here's a short summary of how it works, since the program itself contains a better explanation that you can see when you pass "-h".

Call the program with the scheme as the first parameter (this is the "%1") in the scheme in the registry. Then pass what you want to be run, replacing the to-be-passed data with a "#" followed by the index of the to-be-passed value in the scheme. Since this sounds a bit complicated, here's an example:

In the registry (where python.exe and sliceuri.py's locations will change)
"python.exe" "sliceuri.py" "%1" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--incognito" "#1"

This will be called (when using the URI mychrome://www.google.com) as:
python.exe sliceuri.py "mychrome://www.google.com" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--incognito" "#1"

And will be translated to run:
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe "--incognito" "www.google.com"

**Comment by tbmuc** [comment]
Thank you so much for the script. It works as described. There is only one problem: „/“ is part of almost every URLs.

 

I would like to call different sites from CRM in incognito mode, because the results differ when cookies are set. Here are some examples

 

https://www.aliexpress.com/af/%s.html?g=y <https://www.aliexpress.com/af/%25s.html?g=y&SearchText=%25s&SortType=total_tranpro_desc> &SearchText=%s&SortType=total_tranpro_desc

https://www.facebook.com/search/videos/?q=%s <https://www.facebook.com/search/videos/?q=%25s> 

https://www.amazon.com/s/?field-keywords=%s <https://www.amazon.com/s/?field-keywords=%25s> 

https://trends.google.com/trends/explore?q=%s <https://trends.google.com/trends/explore?q=%25s> 

https://www.youtube.com/results?search_query=%s <https://www.youtube.com/results?search_query=%25s> 

 

Is it possible to remove just the mychrome:// . 

How to pass a SSL request (https://)

 

 

 

 

Von: Sander Ronde <notifications@github.com> 
Gesendet: Dienstag, 5. März 2019 16:37
An: SanderRonde/CustomRightClickMenu <CustomRightClickMenu@noreply.github.com>
Cc: tbmuc <thbenner@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [SanderRonde/CustomRightClickMenu] How can I open a link in chrome incognito tab (#31)

 

I tried to do this myself as well and found that the reason it doesn't work is the following. %1 passes the full matched scheme to the target application. This means that if you run mychrome://abc chrome gets run with "mychrome://abc". Since this is, again, a URI scheme (it's the very same one you passed in the first place), it will basically keep infinitely opening new chrome windows. I assume someone has added a check for that in the chrome code because that's not what happens.

What you can see though, is that if you invalidate the scheme (for example you don't use "%1" but "'%1'" with added quotes inside), it will open the passed URL but it's invalid. Because of this there's no infinite loop and it opens it.

The result here is that it's not directly possible to open a URL in chrome, as chrome gets the whole scheme as a parameter and doesn't know what to do with it. Something you can do though, is to create/use a different program that slices out the custom scheme and then finally calls chrome with the sliced version. Fortunately, I've gone ahead and created a program that does that over here <https://gist.github.com/SanderRonde/4c0ef890bcf3df89864678dfa7204f08> . All you need for the program is python. Here's a short summary of how it works, since the program itself contains a better explanation that you can see when you pass "-h".

Call the program with the scheme as the first parameter (this is the "%1") in the scheme in the registry. Then pass what you want to be run, replacing the to-be-passed data with a "#" followed by the index of the to-be-passed value in the scheme. Since this sounds a bit complicated, here's an example:

In the registry (where python.exe and sliceuri.py's locations will change)
"python.exe" "sliceuri.py" "%1" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--incognito" "#1 <https://github.com/SanderRonde/CustomRightClickMenu/issues/1> "

This will be called (when using the URI mychrome://www.google.com) as:
python.exe sliceuri.py "mychrome://www.google.com" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--incognito" "#1 <https://github.com/SanderRonde/CustomRightClickMenu/issues/1> "

And will be translated to run:
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe "--incognito" "www.google.com <http://www.google.com> "

**Comment by SanderRonde** [comment]
Oh yeah that's actually quite a bit limitation. I've revised the script to take this into account. You can now pass "-s" as the first argument to ignore any slashes past the scheme itself. The URL to the script will be the same, you'll just have to re-download it.

**Comment by tbmuc** [comment]
Great, now ist working. Thank you very much!!!

 

Von: Sander Ronde <notifications@github.com> 
Gesendet: Dienstag, 5. März 2019 18:04
An: SanderRonde/CustomRightClickMenu <CustomRightClickMenu@noreply.github.com>
Cc: tbmuc <thbenner@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [SanderRonde/CustomRightClickMenu] How can I open a link in chrome incognito tab (#31)

 

Oh yeah that's actually quite a bit limitation. I've revised the script to take this into account. You can now pass "-s" as the first argument to ignore any slashes past the scheme itself. The URL to the script will be the same, you'll just have to re-download it.
