### ISSUE TITLE
Feature Request: i18n support

### ISSUE THREAD

**Issue by yfdyh000** [SanderRonde/CustomRightClickMenu#33]
Any thoughts and is it feasible?

**Comment by SanderRonde** [comment]
That sounds like a good idea. It's definitely feasible to do this, implementing it won't be that much work and I think the biggest "problem" is finding people willing to supply translations for their language.

My current plan is to implement i18n support, providing english translations off the bat (since they're already there) and adding a "switch language" icon on the options page. Hopefully people will see it and click the "supply translations for your language" button that I'll add along with it. 

Does this sound good to you? If it does I'll be working on this feature and including it in the next update.
