### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by bumaociyuan** [SanderRonde/CustomRightClickMenu#36]
```
GM_xmlhttpRequest({
  method: 'GET',
  url:'https://somedomain.com',
  onload: function(responseDetails) {
})
```

The script works well before chrome 72

On latest chrome get error as follow

crmapi.js:5 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://somedomain.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by bumaociyuan** [comment]
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

**Comment by SanderRonde** [comment]
Thanks for the issue, this does indeed seem to be a pretty big problem since it blocks all possibilities for creating XHRs. I think it would be best if I created a new method on the CRM API that would make the request through the background page. The `GM_xmlhttpRequest` function is more of a polyfill for tamper/greasemonkey scripts so it should mimic its implementation as much as possible.

I'll be posting details about the new method when I've implemented it so you can use it right away when the new version is released.

**Comment by bumaociyuan** [comment]
@SanderRonde  Thank you for reply

**Comment by SanderRonde** [comment]
I've added the `crmAPI.fetch(url)` and `crmAPI.fetchBackground(url)` functions. The first done does basically the same as `window.fetch` while the second one avoids the CORB problem by doing the fetch through the backgroundpage. They should be available in the next update.
