### ISSUE TITLE
Templates for inputs

### ISSUE THREAD

**Issue by Costegillio** [SanderRonde/CustomRightClickMenu#38]
Greetings!

Is there any way to create some kind of short templates for answer?

For example, i have some chat in facebook and instead of writing answers for my collocutor's questions i'll click on some prepared answers and your extention will append it to the focused textarea?

Thanks for your extension!

**Comment by SanderRonde** [comment]
That should be fairly easy to do. Add a bunch of scripts where every script contains the following code:

```js
crmAPI.contextData.target.value += "mytext";
```

Where you replace mytext with the text you want appended to the textarea. This will, when you right-click on a textarea and click one of the right-click menu entries, append the text to the textarea's contents. You can make as many right-click menu entries/scripts as you want, giving them all a template to use.

This might be a bit unclear since I don't know your proficiency in javascript so please let me know if I didn't explain it that well.

**Comment by Costegillio** [comment]
@SanderRonde, it works, thx you so much!
