### ISSUE TITLE
How to store data?

### ISSUE THREAD

**Issue by erikdemarco** [SanderRonde/CustomRightClickMenu#40]
Hello, I cant find any tutorial to use CRM.

If I already get data that i want via getSelection() and then where we can store the data? So we can use it later.

**Comment by SanderRonde** [comment]
There indeed is not a tutorial for this extension. It's not that big of an extension and a tutorial would have to be very comprehensive

When it comes to storing data you will probably want to look at the [crmAPI.storage API](https://sanderronde.github.io/CustomRightClickMenu/documentation/classes/crm.crmapi.instance.html#storage). With it you can permanently store data for a specific script. If you want to store it for just that website, you can use the localStorage API as well.

**Comment by erikdemarco** [comment]
I try to use basic script like this:

```
var value = "test";
        chrome.storage.local.set({key: value}, function() {
          console.log('Value is set to ' + value);
        });
      
        chrome.storage.local.get(['key'], function(result) {
          console.log('Value currently is ' + result.key);
        });
```

the console shows:
Value is set to test
Value currently is [object]  (empty data)

why "chrome.storage.local.get" doesnt work?
I tick all the permission in "edit script", it got untick itself all the time.

**Comment by SanderRonde** [comment]
That's right, you can't use the `chrome.storage` APIs or any other chrome APIs. That is a security measure to prevent scripts from breaking/changing extension data (you would be writing your data to the same place the extension stores its data). That's why you should use the crmAPI.storage API instead. You can also use the [crmAPI.browser API](https://sanderronde.github.io/CustomRightClickMenu/documentation/classes/crm.crmapi.instance.html#browser) which is supposed to mimic the call signature of those chrome functions.

**Comment by erikdemarco** [comment]
when i'm doing this:

```
        crmAPI.browser.storage.local.set({key: value}, function() {
          console.log('Value is set to ' + value);
        });
      
        crmAPI.browser.storage.local.get(['key'], function(result) {
          console.log('Value currently is ' + result.key);
        });
```

it shows "crmapi.js:5 Looks like you didn't send your chrome function, set crmAPI.warnOnChromeFunctionNotSent to false to disable this message"

do i miss something?

**Comment by SanderRonde** [comment]
You have to call `.send()` at the end. So instead of 
```
crmAPI.browser.storage.local.set({key: value}, function() {
    console.log('Value is set to ' + value);
});
```
do
```
crmAPI.browser.storage.local.set({key: value}, function() {
    console.log('Value is set to ' + value);
}).send();
```

There are some examples in the [documentation i sent](https://sanderronde.github.io/CustomRightClickMenu/documentation/classes/crm.crmapi.instance.html#browser) although the formatting has gone a bit bad.

Also you might want to call `.get()` in the callback of `.set()`, because otherwise the setting operations hasn't completed by the time you're calling `.get()`

**Comment by erikdemarco** [comment]
it shows "Error: Permission storage is not allowed for scripts, please use a CRM API"

I end up using CRM API storage. It works. I think this extension is really really powerful.

Maybe you should add more advanced example code in the tutorial. Currently your tutorial only show very basic code which is too bad because it can do many powerful things.

Btw thank you so much for making this extension. I will continue to learn by mistake. :)

**Comment by SanderRonde** [comment]
Good to hear that you got it working, I didn't know that the browser API didn't work.

I probably should add some more example code but I'm currently a bit busy. I'll try to get to it some time soon.
