### ISSUE TITLE
What is the purpose of "used permission" in edit menu?

### ISSUE THREAD

**Issue by erikdemarco** [SanderRonde/CustomRightClickMenu#41]
What is the purpose of "used permission" in edit menu? we can tick and untick it, but after you close it all value will be unticked even you ticked it before

**Comment by SanderRonde** [comment]
I don't think it's supposed to untick all values when you tick some of them but here's the explanation as to what it is:
This extension is made to accomodate both creating your own scripts and installing external scripts (similar to greasemonkey). Since those have a permissions system and an ability to allow and disallow permissions, this extension has that as well. 
However, all scripts **you** make (and don't install from the internet) get full permissions to do everything (since you probably will trust yourself). That's why it's not really useful for scripts you create yourself unless you plan on distributing them on the internet yourself.
