### ISSUE TITLE
404 on Chome Extension Store

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#44]
https://chrome.google.com/webstore/detail/custom-right-click-menu/onnbmgmepodkilcbdodhfepllfmafmlj

The given chrome extension id is invalid.

And my installed CustomRightClickMenu extension could not works now.

**Comment by SanderRonde** [comment]
Yeah the extension has been suspended from the chrome webstore because their AI flagged it as using more permissions than it should. I appealed and got an automated reponse for 20 emails. Then I finally got an email that said they manually re-reviewed it and reinstated it but somehow it still isn't online on the Chrome web store.

**Comment by pendave** [comment]
I have to reinstall downloaded .CRX from crx4chrome.com and it works now.

**Comment by SanderRonde** [comment]
Great, hopefully the original is back online soon as well. I'll post any updates in this issue when they're available

**Comment by tbodt** [comment]
Might be good to reach out to this guy https://twitter.com/dotproto

**Comment by SanderRonde** [comment]
Thanks for the suggestion. I went to the google groups link he has in his bio and [posted something over there](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/1A--Xsk1cJE). If that doesn't work out or gets ignored I'll try to send him a message on twitter.

**Comment by SanderRonde** [comment]
So I got a reply and it looks like I had to remove another permission. I've done so and re-submitted it for review so it's back to waiting for a while again.

**Comment by SanderRonde** [comment]
I got another reply. Apparently using optional permissions isn't allowed in chrome for this purpose. So access to the `browser`/`chrome` API from userscripts isn't allowed anymore. I've removed the functionality and am going to resubmit it to the store. 

Unfortunately it'll probably take a long while before it's back online since they first have to review my previous submission (you can't cancel previous submissions), and apart from that the whole review process takes even longer due to COVID-19. 

In total I expect it to take one or two months if I'm lucky. In the meantime installing the extension by sideloading the built files in the `releases` tag is possible.

**Comment by SanderRonde** [comment]
Looks like it's finally back, I'll close this issue then
