### ISSUE TITLE
Cannot rename title "Custom Menu" in right click

### ISSUE THREAD

**Issue by rubber4roofs** [SanderRonde/CustomRightClickMenu#50]
When I rename the menu from "Custom Menu" in the extension options it does not save and display in the right click menu on chrome.

**Comment by esprout** [comment]
I'm running into this same issue on firefox...well actually LibreWolf, but should be same for firefox.  Is the ability to rename top level menu disabled in firefox?  The reason for this is when I highlight text, by default the "c" key copies the text rather than opening "Custom Menu," so I want to rename top level menu as "Open Custome Menu" so I can hit the "o" key to expand it.

**Comment by SanderRonde** [comment]
Hey @esprout, yeah this is currently broken in Firefox. You can work around this issue quite easily though, see how [here](https://github.com/SanderRonde/CustomRightClickMenu/issues/67#issuecomment-1261004137). See also [here](https://github.com/SanderRonde/CustomRightClickMenu/wiki/Why-the-extension-isn't-being-updated-(often)-any-more) for why I'm not fixing the bug in the souce code.
