### ISSUE TITLE
Disabling handling of userscript installs

### ISSUE THREAD

**Issue by nathgit** [SanderRonde/CustomRightClickMenu#54]
Can I disable it handling the installation of Greasy Fork userscript installs? I tried the global excludes section but it doesn't even keep the setting. On refresh it's gone.

**Comment by SanderRonde** [comment]
No unfortunately not, I used to have a feature where it would detect whether you had any other userscript handlers installed and disable itself if that was the case but google made me remove it because they said it was bloat.

You can just disable the extension as a whole during the installation and get the same effect though.
