### ISSUE TITLE
Project abandoned or in development

### ISSUE THREAD

**Issue by paradoxicallist** [SanderRonde/CustomRightClickMenu#69]
Nice extension. Just asking if it's still under development or abandoned?

**Comment by SanderRonde** [comment]
Hi, you can consider this project abandoned rather than in development. For a full explanation see [this page](https://github.com/SanderRonde/CustomRightClickMenu/wiki/Why-the-extension-isn't-being-updated-(often)-any-more) of the wiki. I'll leave this issue open as an a way for people with the same question to find it.

**Comment by paradoxicallist** [comment]
Answered.

**Comment by paradoxicallist** [comment]
Answered.

**Comment by paradoxicallist** [comment]
@SanderRonde 
Sorry I missed that part of the comment, dumb me! :)

**Comment by SanderRonde** [comment]
No problem!

**Comment by nanotechnicianhq** [comment]
Thanks for making this in anycase, I use it for Twitch to type hello to new chat visitors and doing bot commands. Thankyou so much :)

**Comment by SanderRonde** [comment]
Thanks for the kind words!
