### ISSUE TITLE
Can you make a screen record video for "Launching programs instead of links" in Windows / MAC?

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#7]
I have no idea how to setup this even after I input something but no effect.

![qq 20170417153304](https://cloud.githubusercontent.com/assets/1331881/25082415/440534d4-2383-11e7-8478-9fcc5c62442e.jpg)

**Comment by pendave** [comment]
There's some extension could do similar way

https://chrome.google.com/webstore/detail/open-with-external-applic/hccmhjmmfdfncbfpogafcbpaebclgjcp

**Comment by SanderRonde** [comment]
It looks like I managed to break all buttons on the options page which is why it may not have worked, a patch is already underway so the button should work again.

Basically the idea is that the first input contains the name and path of the file (so for example "C:\Program Files\chrome\chrome.exe") and the second input contains some name you want to give it, this can be any name you want as long as you remember it.

From then on you can use that name (for example if you input "launchchrome" in the second input), as a link to open. So whenever you now go to launchchrome:// in your address bar, it will open chrome.

So all you really need to do is input the file, a name for it, and then hit the generate button and run that file. I'd love to give you the same instructions for mac but I don't have a mac nor do i have access to one so i can't really do that.
